import time
from .storage import get_storage

class VerificationManager:
    def __init__(self, data_file='data/company_verifications.json'):
        self.storage = get_storage(data_file)
        self.data = self.storage.load()
        if not self.data:
            self.data = {}

    def save_verification(self, ticker, content, metadata=None):
        """
        Save verification result for a ticker.
        
        Args:
            ticker (str): The stock ticker (e.g., 600519.SS)
            content (str): The markdown content generated by AI
            metadata (dict): Additional info like price, pe, timestamp
        """
        if metadata is None:
            metadata = {}
            
        timestamp = time.time()
        record = {
            "ticker": ticker,
            "content": content,
            "timestamp": timestamp,
            "date": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp)),
            **metadata
        }
        
        self.data[ticker] = record
        self.storage.save(self.data)
        return record

    def get_verification(self, ticker):
        """
        Get the latest verification result for a ticker.
        """
        return self.data.get(ticker)
